backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: "static"
public_folder: ""

collections:
- name: "/" # Used in routes, e.g. /admin/collections/recipe
  label: "Home" # Used in the UI
  folder: "src/lang/en/Views" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{home.json}}" # Filename template i.e. title.md
  fields: # The fields for each document, usually in front matter
  - {label: "Title", name: "title", widget: "string"}
