backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: "static"
public_folder: ""

collections:
- name: "pages"
  label: "Pages"
  files:
  - file: "src/lang/en/Views/Home.json"
    label: "About"
    name: "about"
    fields:
    - {label: "jumbotronTitle", name: "jumbotronTitle", widget: "string", default: "home-page"}
