backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: static
public_folder:

collections:
- name: pages
  label: Pages
  files:
  - file: src/lang/en/Views/Home.json
    label: Home
    name: Home
    fields:
    - {label: Jumbotron Title, name: jumbotronTitle, widget: string}
    - {label: Jumbotron Sub Title, name: jumbotronSubTitle, widget: string}
    - label: Testimonials
      name: testimonialsTitle
      widget: list
      fields:
      - {label: Author, name: author, widget: string}
      - {label: Title, name: title, widget: string}
      - {label: Quote, name: quote, widget: string}
    - label: Card Features
      name: cardFeatures
      widget: list
      fields:
        - {label: Name,name: name, widget: string}
        - {label: Title,name: title, widget: string}
        - {label: Text,name: text, widget: string}
        - {label: Sub text,name: subText, widget: string}
        - {label: Image URL,name: img, widget: string}
        - {label: Call To Action,name: callToAction, widget: string}
